// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed client-cert.pem
var resourceClientCertPemData []byte
var resourceClientCertPem = &fyne.StaticResource{
	StaticName:    "client-cert.pem",
	StaticContent: resourceClientCertPemData,
}

//go:embed client-key.pem
var resourceClientKeyPemData []byte
var resourceClientKeyPem = &fyne.StaticResource{
	StaticName:    "client-key.pem",
	StaticContent: resourceClientKeyPemData,
}
